[package]
name = "arrowkv"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://arrowkv.io"
repository = "https://github.com/devillove084/arrowkv"
keywords = ["database", "serverless", "storage-engine"]
categories = [
  "asynchronous",
  "data-structures",
  "database",
  "database-implementations",
]
description = "A serverless storage engine that empowers engineers to build reliable and cost-effective databases."

[workspace]
members = [
  "src/engine/arrow",
  "src/kernel",
  "src/journal",
  "src/storage",
  "src/runtime",
]

[dependencies]
arrow-engine = { version = "0.4.0", path = "src/engine/arrow" }
kernel = { version = "0.4.0", path = "src/kernel" }
journal = { version = "0.4.0", path = "src/journal" }
storage = { version = "0.4.0", path = "src/storage" }
runtime = { version = "0.4.0", path = "src/runtime" }

tokio = { version = "1", features = ["full"] }
