[package]
name = "arrowkv"
version = "0.1.0"
authors = ["luhuanbing <luhuanbing084@gmail.com>"]
description = "A super kv"
license = "Apache-2.0/MIT"
readme = "README.md"
categories = ["kv"]
exclude = [".github", "bors.toml", "/ci/*"]
edition = "2021"

[dependencies]
sysconf = "0.3.4"
errno = "0.2.7"
thiserror = "1.0"
bytes = "1.0"
crc = "1.8"
rand = "0.8.0"
proto = { path = "proto" }
skiplist = { path = "skiplist" }
memmap2 = "0.3"
farmhash = "1.1"
prost = "0.8"
enum_dispatch = "0.3"
crossbeam-channel = "0.5"
parking_lot = "0.11"
typenum = "1.14.0"
arrayvec = "0.7.1"
cfg-if = "1.0.0"
conquer-once = "0.3.2"
memoffset = "0.6.4"
libc = "0.2.102"
kernel32-sys = "0.2"
winapi = "0.2"
lazy_static = "1.4.0"
num_cpus = "1.13.0"

[dev-dependencies]
criterion = "0.3"
tempfile = "3"

[workspace]
members = [
    "proto",
    "skiplist",
    "wormhole",
]

[lib]
name = "arrowkv"
